<!DOCTYPE html>
<html>
    <head>
        <script>
            // Ciudadado de Primera Clase
            const foo = () => {
                console.log("fooExperiencia3");
            }
            foo();  // Invoke it using the variable
            // fooExperiencia3

            function sayHello() {
                return "Hello, ";
            }
            function greeting(helloMessage, name) {
                console.log(helloMessage()+ name);
            }
            // Pass 'sayHello' as an argument to 'greeting' function
            greeting(sayHello, "Desarrollo de Apps - 09");
            // Hello, Desarrollo de Apps - 09!

            function sayHello() {
                return () => {
                    console.log("Hello!");
                }
            }

            // Closure
            function makeFunc() {
                const name = 'Luis Arizaga';
                function displayName() {
                    console.log(name);
                }
                return displayName;
            }

            const myFunc = makeFunc();
            myFunc();

            // Ámbito de función
            function exampleFunction() {
                const x = "declared inside function";  // x can only be used in exampleFunction
                console.log("Inside function");
                console.log(x);
            }

            //console.log(x);  // Causes error

            const x = "declared outside function";
            exampleFunction();
            function exampleFunction() {
                console.log("Inside function");
                console.log(x);
            }
            console.log("Outside function");
            console.log(x);

            function f() {
                try {
                    console.log(0);
                    throw 'bogus';
                } catch (e) {
                    console.log(1);
                    return true; // this return statement is suspended
                    // until finally block has completed
                    console.log(2); // not reachable
                } finally {
                    console.log(3);
                    return false; // overwrites the previous "return"
                    console.log(4); // not reachable
                }
                // "return false" is executed now
                console.log(5); // not reachable
            }
            console.log(f()); // 0, 1, 3, false

            function UserException(message) {
                this.message = message;
                this.name = 'UserException';
            }
            function getMonthName(mo) {
                mo--; // Adjust month number for array index (1 = Jan, 12 = Dec)
                const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul',
                'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
                if (months[mo] !== undefined) {
                    return months[mo];
                } else {
                    throw new UserException('InvalidMonthNo');
                }
            }
            let monthName;
            try {
                // statements to try
                const myMonth = 12;
                monthName = getMonthName(myMonth);
            } catch (e) {
                monthName = 'unknown';
                console.error(e.message, e.name); // pass exception object to err handler
            }

        </script>
    </head>
    <body>

    </body>
</html>
